#!/usr/bin/env bash
# Copy files from client to server
if [[ "$#" < 3 ]]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -eq 3 ]
then
    scp -o StrictHostKeyChecking=no $1 $3@$2:~/
elif [ "$#" -eq 4 ]
then
    scp -i $4 -o StrictHostKeyChecking=no $1 $3@$2:~/
fi
