#!/usr/bin/env bash
#Manages file "manage_my_process"
if [[ $# == 1 ]]
cmd="$1"
then
    if [[ "$cmd" = "start" ]]
    then
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
    elif [[ "$cmd" = "stop" ]]
    then
        kill "$(cat /var/run/my_process.pid)"
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
    elif [[ "$cmd" = "restart" ]]
    then
        kill "$(cat /var/run/my_process.pid)"
        rm /var/run/my_process.pid
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process restarted"
    else
        echo "Usage: manage_my_process {start|stop|restart}"
    fi
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
