#!/usr/bin/env bash
#displays To infinity and beyond indefinitely With a sleep 2 in between each iteration
#trap receives signal
trap "echo I am invincible!!!" SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
