#!/usr/bin/env bash
# read file

while IFS=':' read -r username password _ userid groupid userinfo _ homedir _;
do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $type. $userid's place is protected by the passcode $password, more info about the user here: $userinfo"
done < "/etc/passwd"
