#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
var="Best School"
i=1

while [ $i -lt 11 ]; do
    echo "$var"
     if [ $i -eq 9 ]; then
        echo "Hi"
    fi
    i=$((i + 1))
done
