#!/usr/bin/env bash
#Display 'Best School'10 times with `while` loop but uses if and elif statement to print other str  

i=1
while [ $i -le 10 ]
do
    if [[ $i -eq 4 ]]
    then
        echo "bad luck"
    elif [[ $i -eq 8 ]]
    then
        echo "good luck"
    else
        echo 'Best School'
    fi
    i=$((i+1))
done
