#!/usr/bin/env bash
# This script is displaying the hour and seconds
hour=0
while [ $hour -lt 13 ]; do
    seconds=1
    echo "Hour: $hour"
    while [ $seconds -lt 60 ]; do
        echo "$seconds"
        seconds=$((seconds + 1))
    done
    hour=$((hour + 1))
done
