#!/usr/bin/env bash
# Write a Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed (refer to the example)

files=$(ls)
for file in $files; do
    if [ -e "$file" ] && [ -f "$file" ]; then
        if [[ "$file" == *-* ]]; then
            file_name=$(echo "$file" | cut -d'-' -f2-)
            echo "$file_name"
        fi
    fi
done
