#!/usr/bin/env bash
# Setting up a ufw firewall
sudo apt update
sudo apt install ufw

sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
sudo ufw allow 'Nginx Full'
sudo ufw enable
